### ISSUE TITLE
無駄にインラインスタイルを使わないほうがよいのでは

### ISSUE THREAD

**Issue by wamekukyouzin** [kbc-itw/OctPot#3]
`CharacterManagement.html`にて
html外のCSS読むなら嬉しげにインラインスタイル使わない方が管理上よい

**Comment by Huruikagi** [comment]
これ終わったんなら閉じとけ
ちゃんとissueをメンテしろ
issueをcommitで閉じる癖をつけろ
commitで閉じ忘れたんならwebからcommitへのリンク貼って閉じろ

https://github.com/kbc-itw/OctPot/commit/3e2e0ad9b0d35d423e915e02bb981f17ed5d44fd

こんな感じに
