### ISSUE TITLE
何かのフレームワークの利用検討

### ISSUE THREAD

**Issue by wamekukyouzin** [kbc-itw/OctPot#5]
これゼロから作るのはとても面倒くさいので、AngularなりReactなりVueなり何かしらのフレームワークを勉強したほうがよい

**Comment by kbc16a02** [comment]
Angularを利用します

**Comment by wamekukyouzin** [comment]
なぜ数あるフレームワークの中から特にAngularを利用しようと思ったのですか？
今回のプロジェクトにおいてAngularのどのような点が強みとなると考えましたか？

**Comment by wamekukyouzin** [comment]
っていうかAngularのバージョンいくつ使うの？
